```{r setup, include=FALSE}
#
# title:  "Osoyoos Sockeye Recruitment Estimation"
# author: "Colin Bailey, Patrick Thompson, Howard Stiff"
# date:   '2024-06-24'
# output: html_document
# update: 240124 - revisions to CB's program, replacing 16-to-24-hr BON dam count models with single predictive model
# update: 240124 - included GAM model for imputation of missing 2011 spawn grd sub-stock ratios
# update: 240214 - included GAM model imputation of missing H-O:N-O ratios in 2016 and 2019
# update: 240218 - detailed code documentation added
# update: 240221 - estimate OSO stray rates from spawn grd data in 2009, 2010, 2012; calculate estimates of total annual returns of Skaha Sockeye
# update: 240322 - change predictive model for 16-to-24-hr BON dam counts to a negative binomial model because response variable (difference) is over-dispersed counts
# update: 240227 - 240306 - estimate weighted mean stray rate (~4.6%) for SKA-origin fish staying in the lower Ok River from H-O data in 2018 and 2020, and apply to applicable years.
# update: 240312 - sets SIS-Data-OSOYOOS 24.02.12.xlsx as input file (was v24.01.12.xlsx prior) for returns data and AUC data; no differences in final WRITE stmt output. 
# update: 240408 - recalculates OSO -> SKA and SKA -> OSO stray rates, taking into account the estimated strays. OSO N-O estimates changed by <1% and only in years 2012+.
# update: 240416 - CB review of program; fix for apparent negative proportion N-O in 2011 affecting GAM model
# update: 240426 - fixed bug in filter stmt in chunk {r oso vs ska} that allowed multiple 2011 records (ie filter stmt was disabled in 240416)
# update: 240510 - prep program for csv inputs only (for ultimate upload to GitHub
# update: 240515 - configure for GitHub repository
# update: 240524 + see GitHub
# update: TO DO  - incorporate RY2022 and 2023 data to extend mar-surv time-series to SY2021 - DONE
# update: 240701 - dam counts now retrieved from CBR-DART web data portal - requires execution of "Download Sockeye Dam Counts from CBR-DATA.R"
# update: 240825 - uses CRITFC age comp for all years available, and no ONA age comp from spawning grounds.
#
timestamp <- substr(format(Sys.time(), "%Y%m%d"), 3, 8)                         # Get the current date and time and format as string to timestamp output files

knitr::opts_chunk$set(echo = TRUE)

if (!require(SiREfunctions)) {
  install.packages("devtools")
  install.packages("remotes")
  remotes::install_github("SiRE-P/SiREfunctions")
}
library(beepr)        # for making sounds
library(ggplot2)
library(ggpubr)       # for adding text boxes with regression coefficients to plots
library(ggrepel)
library(rvest)
library(MASS)
library(mgcv)
library(patchwork)
library(psych)
library(RColorBrewer)
library(readxl)
library(reshape2)
library(scales)
library(SiREfunctions)
library(splines)
library(stringi)
library(tidyverse)
library(viridis)

last_year <- 2023     # current last year of returns data handled or available 

```

```{r functions}
cv_gam_loo <- function(data, formula, seed = 123) {
  # Get the number of observations
  n <- nrow(data)
  
  # Create a vector to hold the cross-validated errors
  mse <- numeric(n)
  
  # Loop over the observations
  for(i in 1:n){
    # Split the data into training and testing sets
    train_data <- data[-i, ]  # all but the ith observation
    test_data <- data[i, , drop = FALSE]  # only the ith observation
    
    # Fit the model on the training data
    suppressWarnings(model <- gam(formula, data = train_data, family = binomial(link = "logit")))
    
    # Predict on the test data in response space
    suppressWarnings(predictions_response <- predict(model, newdata = test_data, type = "response"))
    
    # Compute the observed values in response space
    observed_response <- test_data[[as.character(formula[[2]])]]
    
    # Compute the errors
    mse[i] <- (observed_response - predictions_response)^2
  }
  
  # Compute the average errors
  mean_mse <- mean(mse)
  
  # Return the average errors
  return(mean_mse)
}

make_a_sound <- function(noise, pause) {
  beep(sound = noise)
  Sys.sleep(pause)
  beep(sound = noise)
}
```

```{r import harvest} 

workbook <- "Columbia River sockeye harvest (Ryan Lothrop WDFW 240513).xlsx"    # raw USA harvest from WDFW and Okanagan (CAN) harvest by gear
worksheet<- "SockeyeHarvestDataForR"                                            # raw data with easy column headings for R
filename <- paste("../data/", workbook, sep = "")

columbia_sockeye_harvest_data <- read_xlsx(filename, sheet=worksheet) %>%
  janitor::clean_names() %>%  
  filter(!is.na(year), year <= last_year) %>%
  mutate(return_year = year) %>%
  mutate(okanagan_returns = round(okanagan_returns, 0),                         # import summary catch data, %okanagan, and est'd harvest rate 
         okanagan_harvest_rate = round(okanagan_harvest_rate, 3)) %>%           # but for this analysis, 
  dplyr::select(return_year, total_harvest_below_bonn, total_usa_harvest,       # we are only interested in total sockeye harvest below Bonneville... 
                proportion_okanagan, okanagan_sockeye_harvest_usa,               
                okanagan_sockeye_harvest_can, okanagan_sockeye_harvest_total,
                okanagan_returns, okanagan_harvest_rate)

columbia_sockeye_harvest_below_bonn <- columbia_sockeye_harvest_data %>%
  dplyr::select(return_year, total_harvest_below_bonn, proportion_okanagan)     # we are only interested in total sockeye harvest below Bonneville.

columbia_sockeye_harvest_below_bonn[is.na(columbia_sockeye_harvest_below_bonn)] <- 0 
```

```{r import snake sockeye}
workbook <- "Snake River Sockeye from Joint Staff Report.xlsx"                  # estimated Snake River Sockeye component from 
worksheet<- "Snake River Sockeye Estimates"                                     # WDFW/ODFW Joint Staff Report Table 15
filename <- paste("../data/", workbook, sep = "")

snake_sockeye_estimates <- read_xlsx(filename, sheet=worksheet) %>%
  janitor::clean_names() %>%  
  filter(!is.na(year), year <= last_year) %>%
  mutate(return_year = year) %>%
  dplyr::select(return_year, total_snake_sockeye)

```

```{r calculate oka-bound sockeye abundance}

Columbia_Sockeye_Dam_Counts_Adj <-                                              #   Import expanded & adjusted mainstem dam counts
# read.csv("../data/Columbia_Sockeye_Dam_Counts_Adj_240718.csv") %>%            ### <-- requires prior execution of "Download Sockeye Dam Counts from CBR-DATA.R"
# read.csv("../data/Columbia_Sockeye_Dam_Counts_Adj_240908.csv") %>%            ### <-- requires prior execution of "Download Sockeye Dam Counts from CBR-DATA.R"
# read.csv("../data/Columbia_Sockeye_Dam_Counts_Adj_240913.csv") %>%            ### <-- no changes since 240908.csv but 240913 is a benchmark for latest draft report
  read.csv("../data/Columbia_Sockeye_Dam_Counts_Adj_241111.csv") %>%            ### <-- no changes since 240913.csv but 241111 is a benchmark for latest draft report
  janitor::clean_names()                                                        ###     

dam_counts <- Columbia_Sockeye_Dam_Counts_Adj %>%                               
  dplyr::select(return_year,                  bon_sox = bonn_sockeye_adj,       # obtain ADJusted Sockeye estimates from mainstem dams
                rid_sox = rock_i_sockeye_adj, rrh_sox = rrh_sockeye_adj, 
                tum_sox = tum_sockeye_adj,    wel_sox = wells_sockeye_adj)

Columbia_Sockeye_Stock_Comp <- 
# read.csv("../data/Columbia_Sockeye_Stock_Comp_240718.csv") %>%                ### <-- requires prior execution of "Download Sockeye Dam Counts from CBR-DATA.R"
# read.csv("../data/Columbia_Sockeye_Stock_Comp_240908.csv") %>%                ### <-- requires prior execution of "Download Sockeye Dam Counts from CBR-DATA.R"
# read.csv("../data/Columbia_Sockeye_Stock_Comp_240913.csv") %>%                ### <-- no changes since 240908.csv but 240913 is a benchmark for latest draft report
  read.csv("../data/Columbia_Sockeye_Stock_Comp_241111.csv") %>%                ### <-- no changes since 240913.csv but 241111 is a benchmark for latest draft report
  janitor::clean_names()                                                        ###     

stock_comp <- Columbia_Sockeye_Stock_Comp %>% 
  dplyr::select(return_year, ok_stock_comp = ok_stock_comp_best)                # select best annual Okanagan Sockeye stock comp estimates

annual_returns <- dam_counts %>%                                                # get annual Okanagan-bound Sockeye recruitment estimates 
  full_join(columbia_sockeye_harvest_below_bonn, by = "return_year") %>%
  full_join(snake_sockeye_estimates, by = "return_year") %>%
  full_join(stock_comp, by = "return_year") %>%
  dplyr::rename(snake_sox = total_snake_sockeye) %>%
  arrange(return_year) %>%
  mutate(bon_sox = round(bon_sox, 0)) %>%                                       # derive Okanagan-bound Sockeye recruits based on:
  mutate(columbia_sox = bon_sox +                                               #   adjusted Bonneville Sockeye estimates 
         ifelse(is.na(total_harvest_below_bonn),0,total_harvest_below_bonn)) %>%# + downstream harvest (Zones 1-5) in Columbia estuary  
  mutate(mid_columbia_sox = columbia_sox - snake_sox) %>%                       # - Snake Sockeye estimates 
  mutate(oka_sox = round(mid_columbia_sox * ok_stock_comp, 0)) %>%              # x "best" Okanagan-bound stock proportion
  mutate(wen_sox = mid_columbia_sox - oka_sox) %>%
  dplyr::select(return_year, columbia_sox, total_harvest_below_bonn, bon_sox,   
                snake_sox, mid_columbia_sox, 
                ok_stock_comp, wen_sox, oka_sox)
```

```{r proportion hatch and natch}  
# estimates of hatchery numbers      ### NOTE: initial ok_riv_deadpitch import from XLSX should be commented out for final GitHub version. ###

# ok_riv_deadpitch <- readxl::read_xlsx("../data/OSO_SOX_deadpitch_data_tidy 24.05.24.xlsx") %>% # deadpitch for Osoyoos and middle channel fish with        # comment out for GitHub
#   janitor::clean_names()                                                                       # detection of thermal marks (was 24.05.24)                 # comment out for GitHub
# write.csv(ok_riv_deadpitch,  "../data/ok_riv_deadpitch_xlsx_240524.csv")                       # if OSO SOX deadpitch xlsx data imported, re-write to CSV  # comment out for GitHub
# ok_riv_deadpitch_old <- read.csv("../data/ok_riv_deadpitch_xlsx_240524.csv")                   # replaces import data from OSO SOX deadpitch xlsx workbook # keep for GitHub [240510]

filename <- ("C:/DFO-MPO/OneDrive/OneDrive - DFO-MPO/okanagan_data/deadpitch/combined_and_cleaned/okanagan_deadpitch.csv") # revised by AO and PT 2410xx

ok_riv_deadpitch <- read.csv2(filename, sep=",")                    # read cleaned up DP data 

# filename <- paste("../data/ok_riv_deadpitch_", timestamp, ".csv", sep = "")   # make a copy in the OSO recruits DATA folder...
# write.csv(ok_riv_deadpitch, filename)                             # if *NEW* OSO SOX deadpitch data imported, re-write to CSV       ### comment out for GitHub
# ok_riv_deadpitch <- read.csv(filename)                            # replaces import data from OSO SOX deadpitch                     #   keep for GitHub [240510]

deadpitch_prop_natural <- ok_riv_deadpitch %>%                      # get proportion natural by spawning ground section and year
  filter(species_from_age == "sockeye") %>%                         # from revised DP data (PT, AO, 240825)
  filter(hatchery != "unknown") %>%                                 # omit unknown thermal mark class
  mutate(origin = hatchery) %>%                                     # define variable origin based on hatchery = "natural" or "hatchery"
  dplyr::select(section, year, origin, ona_number) %>% 
  group_by(section, year) %>% 
  summarize(n_natural = sum(origin == "natural"), n = n()) %>%      # get count of natural origin fish by section and year
  mutate(p_nat = n_natural / n) %>%                                 # calculate proportion N-O (natural)
  mutate(testalinden_spill = ifelse(year == 2013, TRUE, FALSE))%>%  # 2010 Testalinden dam failure might affect juvs in Osoyoos Lk mainly returning in 2013
  mutate(testalinden_spill = ifelse(section == "lower_ok_river",     
                                    testalinden_spill, NA))%>%    
  mutate(section = ifelse(section == "shingle creek", "shingle_creek", section)) %>%
  arrange(section, year)                                          

# deadpitch_2022_2023 <- data.frame(                                ### append summary values for 2022 and 2023 till raw data obtained [24.07.04]
#   year = c(2022, 2023, 2022, 2022),                               
#   section = c("Lower Ok River", "Lower Ok River",                   # Lower Ok River
#               "Penticton Channel", "Shingle Creek"),                # Skaha River and Shingle Creek section
#   n_natural = c(388, 311, 360, 35),                               ### natural origin count from AO
#           n = c(392, 322, 368, 57)) %>%                           ### total deadpitch from AO 
#   mutate(p_nat = n_natural / n) %>%                               ### still no 2023 data for mid/upper/shingle?
#   mutate(osoyoos_stocked = FALSE)

#run cross validation to determine df of year spline
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "lower_ok_river"), formula = p_nat ~ bs(year, 3))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "lower_ok_river"), formula = p_nat ~ bs(year, 4))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "lower_ok_river"), formula = p_nat ~ bs(year, 5))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "lower_ok_river"), formula = p_nat ~ bs(year, 6))
#lowest MSE is for model with 3 df on spline

cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "middle_ok_river"), formula = p_nat ~ bs(year, 3))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "middle_ok_river"), formula = p_nat ~ bs(year, 4))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "middle_ok_river"), formula = p_nat ~ bs(year, 5))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "middle_ok_river"), formula = p_nat ~ bs(year, 6))
#lowest MSE is for model with 5 df on spline

cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_nat ~ bs(year, 3))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_nat ~ bs(year, 4))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_nat ~ bs(year, 5))
cv_gam_loo(data = deadpitch_prop_natural %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_nat ~ bs(year, 6))
#lowest MSE is for model with 3 df on spline 

# fit gam to impute missing values
pnat_low_m <- gam(p_nat ~ bs(year, 3), data = deadpitch_prop_natural %>% filter(section == "lower_ok_river") , family = binomial(link = "logit"))
pnat_mid_m <- gam(p_nat ~ bs(year, 5), data = deadpitch_prop_natural %>% filter(section == "middle_ok_river"), family = binomial(link = "logit"))
pnat_pen_m <- gam(p_nat ~ bs(year, 3), data = deadpitch_prop_natural %>% filter(section == "upper_ok_river") , family = binomial(link = "logit"))

deadpitch_prop_natural_filtered <- deadpitch_prop_natural %>%
  filter(section != "ok_lake_creeks")

ggplot(deadpitch_prop_natural_filtered, aes(x = year, y = p_nat))+
  geom_point() +
  # geom_point(aes(color = osoyoos_stocked))+
  # geom_line(data = data.frame(section = "lower_ok_river", year = 2007:last_year, 
  #                             p_nat = predict(pnat_low_m, data.frame(year = 2007:last_year, osoyoos_stocked = FALSE), type = "response")))+
  # geom_line(data = data.frame(section = "middle_ok_river", year = 2009:last_year, 
  #                             p_nat = predict(pnat_mid_m, data.frame(year = 2009:last_year, osoyoos_stocked = FALSE), type = "response")))+
  geom_line(data = data.frame(section = "lower_ok_river", year = 2007:last_year, 
                              p_nat = predict(pnat_low_m, data.frame(year = 2007:last_year), type = "response")))+
  geom_line(data = data.frame(section = "middle_ok_river", year = 2009:2018, 
                              p_nat = predict(pnat_mid_m, data.frame(year = 2009:2018),      type = "response")))+
  geom_line(data = data.frame(section = "upper_ok_river", year = 2011:last_year, 
                              p_nat = predict(pnat_pen_m, data.frame(year = 2011:last_year), type = "response")))+
  facet_wrap(~section, ncol=2)+
  scale_x_continuous(breaks = c(seq(from = 2007, to = last_year, by = 2)))+
  theme_pt(major_grid=TRUE) +
  theme(legend.position = "bottom", legend.title = element_text(size=9),
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

#add in imputed values
prop_natural <- bind_rows(deadpitch_prop_natural_filtered %>% mutate(type = "Sampled"), 
                          
                data.frame(year = c(2019), section = "lower_ok_river",  type = "Imputed", 
                           p_nat = predict(pnat_low_m, data.frame(year = c(2019)), type = "response")),
                
                data.frame(year = c(2009), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2009)), type = "response")), #) %>%
                data.frame(year = c(2016), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                data.frame(year = c(2019), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                data.frame(year = c(2020), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                data.frame(year = c(2021), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                data.frame(year = c(2022), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                data.frame(year = c(2023), section = "middle_ok_river", type = "Imputed", 
                           p_nat = predict(pnat_mid_m, data.frame(year = c(2016)), type = "response")), #) %>%
                
                data.frame(year = c(2023), section = "upper_ok_river",  type = "Imputed",
                           p_nat = predict(pnat_pen_m, data.frame(year = c(2023)), type = "response"))) %>%
  
  mutate(section_label = ifelse(section == "lower_ok_river",  "Lower Okanagan River", section)) %>%
  mutate(section_label = ifelse(section == "middle_ok_river", "Middle Okanagan River", section_label)) %>%
  mutate(section_label = ifelse(section == "upper_ok_river",  "Penticton Channel", section_label)) %>%
  mutate(section_label = ifelse(section == "shingle_creek",   "Shingle Creek", section_label)) %>%
  mutate(section_label = ifelse(section == "shingle creek",   "Shingle Creek", section_label)) %>%
  mutate(spawning_location = ifelse(section == "shingle_creek",   "Shingle Creek", "Unknown")) %>%
  mutate(spawning_location = ifelse(section == "shingle creek",   "Shingle Creek", spawning_location)) %>%
  mutate(spawning_location = ifelse(section == "lower_ok_river",  "Lower Ok River", spawning_location)) %>%
  mutate(spawning_location = ifelse(section == "middle_ok_river", "Middle Ok River", spawning_location)) %>%
  mutate(spawning_location = ifelse(section == "upper_ok_river",  "Penticton Channel", spawning_location)) %>%
  mutate(prop_nat_type = type) %>%
  arrange(section_label, year)

ggplot(prop_natural, aes(x = year, y = p_nat))+
  geom_line()+
  geom_point(aes(color = prop_nat_type))+
  facet_wrap(~section_label, ncol=2)+
  scale_x_continuous(breaks = c(seq(from = 2007, to = last_year, by = 2)))+
  labs(title="Proportion Natural Origin")+
  ylab("Proportion")+
  xlab(NULL)+
  labs(type="Sample Type")+                                                     # label for legend? ### doesn't work
  theme_pt(major_grid=TRUE)+
  theme(legend.position = "bottom", 
        legend.title = element_blank(),    
        legend.text = element_text(size = 10),              
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

filename <- paste("../figures/Prop_Nat_Origin_", timestamp, ".png", sep = "")   # filename for figure output 
ggsave(file = filename, width = 6, height = 6, units = "in")                    # saves the plot to filename

#prop_natural_oso <- prop_natural %>%                                           # get just prop natural osoyoos
#  filter(section == "Lower Ok River")
```  

```{r SK vs KO}  

deadpitch_prop_sockeye <- ok_riv_deadpitch %>%                        # get proportion Sockeye vs Kokanee by spawning ground section and year
  filter(species_from_age %in% c("sockeye", "kokanee")) %>%           # from revised DP data (PT, AO, 240825)
  # filter(hatchery != "unknown") %>%                                 # omit unknown thermal mark class
  mutate(species = species_from_age) %>%
  mutate(origin = hatchery) %>%                                       # define variable origin based on hatchery = "natural" or "hatchery"
  dplyr::select(section, year, species, origin, ona_number) %>%       # at this stage we can include Sockeye of any origin (H-O or N-O) since
  group_by(section, year) %>%                                         # we're interested in simply accounting for (removing) the percent KO from AUC nerkids
  summarize(n_sockeye = sum(species == "sockeye"), n = n()) %>%       # get count of Sockeye by section and year
  mutate(p_sockeye = n_sockeye / n) %>%                               # calculate proportion Sockeye (H-O and N-O) ### NOTE: only applies to Pen Ch and Shingle [241128]
  mutate(testalinden_spill = ifelse(year == 2013, TRUE, FALSE))%>%    # 2010 Testalinden dam failure might affect juvs in Osoyoos Lk mainly returning in 2013
  mutate(testalinden_spill = ifelse(section == "lower_ok_river", testalinden_spill, NA)) %>%
  arrange(section, year)   
                                                                    ### species_from_age data not available for mid-OkR for 2016, 2019-2023 [241108], so GAM it.. 
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "middle_ok_river") %>% filter(year>2008), formula = p_sockeye ~ bs(year, 3))
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "middle_ok_river") %>% filter(year>2008), formula = p_sockeye ~ bs(year, 4)) # 4DF best [241108]
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "middle_ok_river") %>% filter(year>2008), formula = p_sockeye ~ bs(year, 5))
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "middle_ok_river") %>% filter(year>2008), formula = p_sockeye ~ bs(year, 6))
p_sock_mid_m   <- gam(p_sockeye ~ bs(year, 4), data = deadpitch_prop_sockeye %>% filter(section == "middle_ok_river") , family = binomial(link = "logit"))

                                                                    ### species_from_age data not yet available for 2023 Pen Chan [241108], so GAM it.. 
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_sockeye ~ bs(year, 3))
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_sockeye ~ bs(year, 4)) # 4DF best [241108]
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_sockeye ~ bs(year, 5))
cv_gam_loo(data = deadpitch_prop_sockeye %>% filter(section == "upper_ok_river") %>% filter(year>2011), formula = p_sockeye ~ bs(year, 6))
p_sock_pen_m   <- gam(p_sockeye ~ bs(year, 4), data = deadpitch_prop_sockeye %>% filter(section == "upper_ok_river") , family = binomial(link = "logit"))

deadpitch_prop_sockeye_plus <- bind_rows(deadpitch_prop_sockeye %>% mutate(type = "Observed"),                       ### apply imputed estimate for multiple years for mid-OkR
                               data.frame(year = c(2009), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2009)), type = "response")),
                               data.frame(year = c(2016), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2016)), type = "response")),
                               data.frame(year = c(2019), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2019)), type = "response")),
                               data.frame(year = c(2020), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2020)), type = "response")),
                               data.frame(year = c(2021), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2021)), type = "response")),
                               data.frame(year = c(2022), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2022)), type = "response")),
                               data.frame(year = c(2023), section = "middle_ok_river", type = "Assumed", 
                               p_sockeye = predict(p_sock_mid_m, data.frame(year = c(2023)), type = "response")),
                               
                               data.frame(year = c(2023), section = "upper_ok_river",  type = "Imputed",             ### apply imputed estimate for Pen Ch in 2023
                               p_sockeye = predict(p_sock_pen_m, data.frame(year = c(2023)), type = "response"))) %>%
  
  mutate(prop_sock_type = type) %>%
  dplyr::select(-type) %>%
  arrange(section, year)

# osoyoos vs. skaha data     ### NOTE: initial AUC_data_Import import from XLSX should be commented out for final GitHub version. ###

# AUC_data_Import <- readxl::read_xlsx("../data/SIS - Data - OSOYOOS - 24.06.24.xlsx", sheet = "OK AUC and Deadpitch Results") %>%                           
#   janitor::clean_names()   # comment out for GitHub
# write.csv(AUC_data_Import,  "../data/AUC_data_Import_xlsx_240624.csv")        # if AUC_data imported from SIS xlsx workbook, re-write to CSV   # comment out for GitHub

#UC_data_Import <- read.csv("../data/AUC_data_Import_xlsx_240624.csv")            # replaces AUC data from SIS xlsx workbook (was 240516)          # keep for GitHub [240510]
#UC_data_Import <- read.csv("../data/AUC_data_Import_xlsx_240624 - wkg (AO).csv") # AO checking nerkid estimates and providing updates (241101)    # keep for GitHub [240510]
#UC_data_Import <- read.csv("../data/AUC_data_Import_xlsx_241105_AO.csv")         # AO checking nerkid estimates and providing updates (241105)    # keep for GitHub [240510]

AUC_data_Import <- readxl::read_xlsx("../data/AUC_data_Import_xlsx_241105_AO.xlsx", sheet = "AUC_data_Import") %>% 
                   janitor::clean_names() %>% 
                   mutate_at("auc", as.numeric) %>%
                   mutate_at("spawning_nerkids", as.numeric) %>%
                   mutate_at("percent_35cm_fl", as.numeric) %>%
                   mutate(bad_estimate = ifelse(year == 2011, spawning_nerkids, NA)) %>%         # store 2011 value...
                   mutate(spawning_nerkids = ifelse(year == 2011, NA, spawning_nerkids)) %>%     # nerkids in 2011 set to NA
                   mutate(spawning_nerkids_note = ifelse(spawning_location %in%                  # flag issue spawning_nerkids=SK for L- and M-OkR but SK & KO for Upper [241128]
                                                  c("Lower Ok River", "Middle Ok River"), "Nerkids = Sockeye only", "Nerkids = Sockeye & Kokanee")) %>%
                   mutate(spawning_nerkids_note = ifelse(is.na(spawning_nerkids), "No estimate", spawning_nerkids_note)) %>%
                   mutate(spawning_nerkids_note = ifelse(year == 2011, paste("Poor survey estimate (", bad_estimate, ") omitted"), spawning_nerkids_note)) %>%
                   mutate(spawning_sockeye = ifelse(spawning_location %in% c("Lower Ok River", "Middle Ok River"), spawning_nerkids, NA)) %>%
                   dplyr::select(rearing_lake, spawning_location, year, auc, spawning_nerkids, spawning_nerkids_note, spawning_sockeye, percent_35cm_fl)

write.csv(AUC_data_Import,  "../data/AUC_data_Import_241128.csv")        # if AUC_data imported from AO xlsx workbook, re-write to CSV   # comment out for GitHub
auc_data_import <- read.csv("../data/AUC_data_Import_241128.csv")        # export and re-import (NOTE lower-case dataset name) --- keep for GitHub [241128]

AUC_data <- auc_data_import %>% 
  filter(year <= last_year) %>%                                                                        ### removing 2011 which was previously imputed, 
  mutate(section = ifelse(spawning_location == "Lower Ok River",    "lower_ok_river", "Unknown"))%>%
  mutate(section = ifelse(spawning_location == "Middle Ok River",   "middle_ok_river", section)) %>%   # changing mid-OkR SK rearing lake to Skaha based on direction from H. Stiff.
  mutate(section = ifelse(spawning_location == "Penticton Channel", "upper_ok_river",  section)) %>%
  mutate(section = ifelse(spawning_location == "Shingle Creek",     "shingle_creek",   section)) %>%
  mutate(rearing_lake = ifelse(spawning_location == "Middle Ok River", "Skaha", rearing_lake)) %>%     # assigns spawners in middle channel as Skaha-reared     
  mutate(percent_35cm_fl = ifelse(year == 2023 & section == "upper_ok_river" & is.na(percent_35cm_fl), 0.80, percent_35cm_fl)) %>%   ### Pen Ch. fish not yet ecotyped via age, so substituting pivot estimate
  dplyr::select(section, year, spawning_location, rearing_lake, spawning_nerkids, percent_35cm_fl, spawning_sockeye, spawning_nerkids_note, -X) %>% # to Skaha (assumed rearing lake of origin) for purposes of
  arrange(section, year)                                                                               # calculating OSO vs SKA proportion [PT 240221]  
                                                                                                       
spawning_location_compare <- AUC_data %>% 
  mutate(old_prop_sock = 1 - percent_35cm_fl, old_total_sockeye = spawning_nerkids * old_prop_sock) %>% 
# left_join(., deadpitch_prop_sockeye,      by = c("section", "year")) %>%
  left_join(., deadpitch_prop_sockeye_plus, by = c("section", "year")) %>%                             # use dataset with imputed mid-OkR and 2023 Pen Chan %sockeye
  mutate(p_sockeye = ifelse(section %in% c("lower_ok_river", "middle_ok_river"), 1, p_sockeye)) %>%
  mutate(total_sockeye = spawning_nerkids * p_sockeye) %>%
# group_by(year, rearing_lake, spawning_location) %>% 
  group_by(year, rearing_lake, spawning_location, prop_sock_type) %>% 
  summarise(nerkids = round(sum(spawning_nerkids)),
            p_sock_len35 = round(sum(old_prop_sock),2),
            total_sockeye_old = round(sum(old_total_sockeye)),
            p_sock_deadp = round(sum(p_sockeye),2),
            total_sockeye = round(sum(total_sockeye   ))) %>% arrange (rearing_lake, spawning_location, year) %>%
  
  mutate(prop_sock_type= ifelse(year == 2000, "Assumed", prop_sock_type)) %>%                     # Nerkids observed, %sox=1 based on visual survey methods confidence [241128]
  mutate(prop_sock_type= ifelse(is.na(prop_sock_type), "Unresolved", prop_sock_type)) %>%                        
  mutate(sockeye_est   = ifelse(!is.na(total_sockeye), prop_sock_type, "Unresolved")) %>%         # Missing nerkid estimate

### fill in some total_sockeye blanks where no %sox in deadpitch available but we can assume 100% sockeye for the few numbers of fish from AUC 
  # e.g., no deadpitch in LOkR in 2000, but assume 100% Sockeye...
# mutate(prop_sock_type= ifelse(year == 2000, "Assumed", prop_sock_type)) %>%                     # Nerkids observed, %sox assumed
# mutate(p_sock_deadp  = ifelse(year == 2000 & is.na(p_sock_deadp), 1, p_sock_deadp)) %>%         # Nerkids observed, %sox assumed 
# mutate(total_sockeye = ifelse(year == 2000 & is.na(total_sockeye), nerkids, total_sockeye)) %>% # Nerkids observed, #sox assumed since %sox assumed
# mutate(sockeye_est   = ifelse(year == 2000, "Assumed", sockeye_est)) %>%                        # Nerkids observed, %sox assumed

# # e.g., no deadpitch in mOkR in 2009, 2016, 2019-2023, but few fish, assume 100% Sockeye...
# mutate(p_sock_deadp  = ifelse(year %in% c(2009, 2016, 2019:last_year) & 
#                        spawning_location == "Middle Ok River"  & is.na(p_sock_deadp), 1, p_sock_deadp)) %>%                         # Nerkids observed, %sox assumed 
# mutate(total_sockeye = ifelse(year %in% c(2009, 2016, 2019:last_year) & 
#                        spawning_location == "Middle Ok River"  & is.na(total_sockeye), nerkids * p_sock_deadp, total_sockeye)) %>%  # Nerkids observed, #sox assumed since %sox assumed
# mutate(sockeye_est   = ifelse(year %in% c(2009, 2016, 2019:last_year) & 
#                        spawning_location == "Middle Ok River" , "Assumed", sockeye_est)) %>%                                        # Nerkids observed, %sox assumed
  
# mutate(total_sockeye = ifelse(spawning_location == "Lower Ok River"  & year == 2022,     ### Hardwire section/years where summary data available
#                               75437, total_sockeye)) %>%                                   # AUC now exists for 2022, so hardwire unnecessary [241025]
  
### no AUC for 2023, so hardwire total OSO spawners = 17238 and 
###                              total SKA spawners = 14450 based on preliminary summary data [from AO 240322]  
# mutate(sockeye_est   = ifelse(is.na(total_sockeye) & spawning_location == "Lower Ok River" & year == 2023, 
#                               "Raw data N/A", sockeye_est)) %>%
# mutate(total_sockeye = ifelse(sockeye_est == "Raw data N/A" & spawning_location == "Lower Ok River" & year == 2023, 
#                               17238, total_sockeye)) %>%                                 
# mutate(sockeye_est   = ifelse(is.na(total_sockeye) & spawning_location == "Penticton Channel" & year == 2023,
#                               "Raw data N/A", sockeye_est)) %>%
# mutate(total_sockeye = ifelse(sockeye_est == "Raw data N/A" & spawning_location == "Penticton Channel" & year == 2023,
#                               14550, total_sockeye)) %>%      
# mutate(sockeye_est   = ifelse(is.na(total_sockeye) &      spawning_location == "Penticton Channel" & year == 2023, ### deadpitch %SK n/a because deadpitch age data n/a          [241107]
#                               "Len>35cm", sockeye_est)) %>%                                                        ### so flag as based on Length cutoff of 35 cm   
# mutate(p_sock_deadp  = ifelse(sockeye_est == "Len>35cm" & spawning_location == "Penticton Channel" & year == 2023, ### and use %SK based on length until age data available [241107]
#                              p_sock_len35, p_sock_deadp)) %>%
# mutate(total_sockeye = ifelse(sockeye_est == "Len>35cm" & spawning_location == "Penticton Channel" & year == 2023, ### and use #SK estimate based on lengths until age data available [241107]
#                               nerkids * p_sock_len35, total_sockeye)) %>%

  dplyr::select(rearing_lake, spawning_location, year, nerkids, p_sock_len35, total_sockeye_old, p_sock_deadp, prop_sock_type, total_sockeye, sockeye_est) %>%
  arrange (rearing_lake, spawning_location, year)

# ggplot(spawning_location_compare, aes(x=year)) +                              # comparing length-based to species_from_age-based
#   ggtitle("Proportion Sockeye vs Kokanee") +
#   facet_wrap(~spawning_location, ncol=2) + #, scales="free_y") +
#   geom_line (aes(y = p_sock_len35), color = "gray") +
#   geom_line (aes(y = p_sock_deadp), color = "blue", linetype=2, size=1) +
#   geom_point(aes(y = p_sock_len35), color = "gray") +
#   geom_point(aes(y = p_sock_deadp, color = "blue")) +
#   labs(x=NULL, y="Percent Sockeye") +
#   scale_x_continuous(breaks = c(seq(from = 2000, to = last_year, by = 4)))+
#   scale_color_manual(values = c("Sockeye %" = "blue", "Old Sockeye %" = "gray")) +
#   theme_minimal() +
#   theme_pt(major_grid=TRUE) +
#   theme(legend.position = "bottom", legend.title = element_text(size=9),
#         legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

ggplot(spawning_location_compare %>% filter(sockeye_est != "Unresolved"), aes(x=year)) +
  ggtitle("Sockeye Spawner Abundance", subtitle = "by Return Year") + 
  facet_wrap(~spawning_location, ncol=2) + #, scales="free_y") +
  geom_line (aes(y = total_sockeye), color = "blue") + #, linetype=1, size=1) +
  geom_point(aes(y = total_sockeye, shape = sockeye_est), size=2) +
  scale_shape_manual(values = c("Assumed"=6, "Imputed"=0, "Observed"=1)) +
# scale_color_manual(values = c("Assumed"="cyan", "Imputed"="red", "Observed"="black")) +
# geom_line (aes(y = total_sockeye_old), color = "gray", size=1) +
# geom_line (aes(y = total_sockeye), color = "blue", linetype=2, size=1) +
# geom_point(aes(y = total_sockeye_old), color = "gray") +
# geom_point(aes(y = total_sockeye, color = sockeye_est)) +
  labs(x=NULL, y="Total Sockeye") +
  labs(shape = "Sockeye Estimate:") +  
  scale_x_continuous(breaks = c(seq(from = 2000, to = last_year, by = 4)))+
# scale_color_manual(values = c("Total Sockeye" = "blue", "Old Total" = "gray")) +
  theme_minimal() +
  theme_pt(major_grid=TRUE) +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5)) +            # theme_pt centers main title but not subtitle
  theme(legend.position = "bottom", legend.title = element_text(size=9),
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

filename <- paste("../figures/Sockeye_Spawners_", timestamp, ".png", sep = "")  # filename for figure output 
ggsave(file = filename, width = 6, height = 6, units = "in")                    # saves the plot to filename

ggplot(data = filter(spawning_location_compare, prop_sock_type != "Unresolved"), aes(x=year)) +
  ggtitle("Proportion Sockeye vs Kokanee", subtitle = "by Return Year") +
  facet_wrap(~spawning_location, ncol=2) + #, scales="free_y") +
  geom_line (aes(y = p_sock_deadp), color = "blue") + #, size=1) +
  geom_point(aes(y = p_sock_deadp, shape = prop_sock_type), size=2) +
  scale_shape_manual(values = c("Assumed"=6, "Imputed"=0, "Observed"=1)) +
#  scale_color_manual(values = c("black", "blue", "black")) +  # Set colors
#  guides(color = guide_legend(override.aes = list(fill = c("white", "blue", "white")))) +  # Set fill colors for legend
  labs(x=NULL, y="Percent Sockeye") +
  scale_x_continuous(breaks = c(seq(from = 2000, to = last_year, by = 4)))+
  theme_minimal() +
#  scale_color_brewer(palette = "Set1") +
#  guides(color = guide_legend(override.aes = list(shape = c(0, 22, 19)))) +  # Merge legends
  labs(shape = "Sockeye Proportion:") +  
  theme_pt(major_grid=TRUE) +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5)) +            # theme_pt centers main title but not subtitle
  theme(legend.position = "bottom", legend.title = element_text(size=9),
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

filename <- paste("../figures/Prop_Sockeye_", timestamp, ".png", sep = "")   # filename for figure output 
ggsave(file = filename, width = 6, height = 6, units = "in")                    # saves the plot to filename

spawning_location <- spawning_location_compare %>%                                                 
  dplyr::select(rearing_lake, spawning_location, year, nerkids, p_sock_deadp, total_sockeye) # trim dataframe to revised estimates

``` 

```{r oso vs ska}  

prop_oso_strays_by_year <- spawning_location %>%          # calculate OSO stray rate based on years where no SKA N-O returns exist (2009-2012)
  filter(year > 2008, year < 2013) %>%                    # N-O fish in mid-OkR from 2009-2012 MUST be OSO strays, since McIntyre dam prevented N-O SKA to spawn <2009, ie N-O Skaha only >= 2013
  left_join(prop_natural %>% dplyr::select(year, spawning_location, p_nat, prop_nat_type)) %>% 
  mutate(natural_sockeye = round(total_sockeye * p_nat)) %>% 
  filter(year != 2011) %>%
  group_by(year) %>%                                      # for true stray rate, include OSO strays in the denominator [PT 240411]
  summarise(strays = sum(natural_sockeye[spawning_location == "Middle Ok River"], 
                         natural_sockeye[spawning_location == "Penticton Channel"]),  # this stmt includes 2012 N-O fish in Pen Chn
                     lower_river = natural_sockeye[spawning_location == "Lower Ok River"], 
                     prop_oso_strays = strays/(lower_river + strays)) %>% 
  filter(!(is.na(prop_oso_strays))) %>%
  mutate(spawning_location = "Lower Ok River")

prop_oso_strays_mean <- sum(prop_oso_strays_by_year$strays)/sum(prop_oso_strays_by_year$lower_river)    # weighted mean stray rate (available years 2010,2012) = 2.69%

prop_oso_strays <- prop_oso_strays_by_year %>% 
  dplyr::select(-strays, -lower_river) %>% 
  bind_rows(data.frame(spawning_location = "Lower Ok River", year = 2013:last_year,  # apply mean OSO stray rate to later years (was 2013:2021)
                       prop_oso_strays = prop_oso_strays_mean)) %>%
  bind_rows(data.frame(spawning_location = "Lower Ok River", year = 2011,            # add in mean stray rate for 2011
                       prop_oso_strays = prop_oso_strays_mean)) %>%
  arrange(year)
```  

```{r ska strays} 

#  H-O fish in lower-OkR from 2018-2021 likely SKA or OKA strays, from which we can calc annual & weighted Multi-Yr avg "SKA stray rate" relative to total H-O on all SGs 
#  PLT - calculate proportion of all HO in lower river in each year of available data
prop_ska_strays_by_year <- prop_natural %>% 
  filter(year >=2018, year <= 2020) %>%                                                    # based on 2018 and 2020 only (2019 insufficient data?)
  filter(!is.na(n)) %>%
  mutate(rearing_lake = ifelse(spawning_location == "Lower Ok River", "Osoyoos", "Skaha")) %>% 
  group_by(year, rearing_lake) %>% 
  summarise(lake_HO = sum(n-n_natural)) %>% 
  spread(key = rearing_lake, value = lake_HO) %>% 
  mutate(prop_ska_strays = Osoyoos/(Skaha + Osoyoos)) %>% 
  filter(!is.na(Osoyoos)) %>%
  filter(!is.na(prop_ska_strays))                                               # no HO:NO data for 2020, so now down to 1 year of stray data: 2018

wmean_ska_stray_prop <- sum(prop_ska_strays_by_year$Osoyoos)/(sum(prop_ska_strays_by_year$Skaha) + sum(prop_ska_strays_by_year$Osoyoos))  # 5.78% (based on 2018, 2020) 

prop_ska_strays <- prop_ska_strays_by_year %>%                                             # get year-specific SKA stray rates (for 2018 and 2020)
  dplyr::select(-Osoyoos, -Skaha) %>% 
  bind_rows(data.frame(year = c(2009:2010, 2011, 2012:2017,2019,2021:last_year),           # apply mean stray rate to other years (was 2012:2021)
                       prop_ska_strays = wmean_ska_stray_prop)) %>%                        # included 2009-2010 and 2011 [241108]
  arrange(year)

# prop_ska_strays_by_year_v2 <- prop_natural %>% 
#   filter(year >=2018, year <= 2020) %>%                                                    # based on 2018 and 2020 only (2019 insufficient data?)
# # filter(!is.na(n)) %>%
#   mutate(rearing_lake = ifelse(spawning_location == "Lower Ok River", "Osoyoos", "Skaha")) %>% 
#   group_by(year, rearing_lake) %>% 
#   filter(rearing_lake == "Osoyoos")
# 
# prop_ska_strays_v2 <- prop_ska_strays_by_year_v2 %>%                                             # get year-specific SKA stray rates (for 2018 and 2020)
#   dplyr::select(-Osoyoos, -Skaha) %>% 
#   bind_rows(data.frame(year = c(2012:2017,2019,2020:last_year),                            # apply mean stray rate to other years (was 2012:2021)
#                        prop_ska_strays = wmean_ska_stray_prop)) %>%
#   arrange(year)

```

```{r prop_nat_origin after strays} 

spawning_table <- spawning_location %>%                                                    # populate Spawning Table from AUC count of spawners in...   
  left_join(prop_natural %>% dplyr::select(year, spawning_location, p_nat)) %>%            # ...lower (Osoyoos) and upper (Skaha) sections of the river
  mutate(p_nat = round(ifelse(is.na(p_nat) & rearing_lake == "Osoyoos", 1, p_nat),3)) %>%  # apply proportion N-O to OSO spawners 
  # mutate(total_sockeye = ifelse(spawning_location == "Lower Ok River"    & year == 2022, 
  #                               75437, total_sockeye)) %>%                               # AUC now exists for 2022, so hardwire unnecessary [241025]
  # mutate(total_sockeye = ifelse(spawning_location == "Lower Ok River"    & year == 2023, 
  #                               17238, total_sockeye)) %>%                               ### no AUC for 2023, so hardwire total OSO spawners [AO 240322]
  # mutate(total_sockeye = ifelse(spawning_location == "Penticton Channel" & year == 2023, 
  #                               14550, total_sockeye)) %>%                               ### no AUC for 2023, so hardwire total SKA spawners [AO 240322]
  mutate(natural_sockeye = round(total_sockeye * p_nat)) %>%
  mutate(section = ifelse(spawning_location == "Lower Ok River",    "lower_ok_river", "upper_ok_river")) %>%  
  mutate(section = ifelse(spawning_location == "Middle Ok River",   "middle_ok_river", section)) %>%
  mutate(section = ifelse(spawning_location == "Penticton Channel", "upper_ok_river",  section)) %>%
  filter(spawning_location != "Shingle Creek")                                             # omit Shingle Creek because of low numbers & data quality
  
spawn_table_summary <- spawning_table %>%                                                  # calculate N-O abund based on proportion N-O  
  group_by(rearing_lake, year) %>% 
  summarise(total_sockeye = sum(total_sockeye), natural_sockeye = sum(natural_sockeye))    # aggregate by rearing lake
# mutate(p_nat = natural_sockeye / total_sockeye)                                          # re-estimates proportion natural by sub-stock & year

stray_correct <- function(obs_focal, obs_other, stray_focal, stray_other){                 # function to adjust for strays in both directions
  max(0,((stray_other - 1) * obs_focal + stray_other * obs_other)/(stray_focal + stray_other - 1))}

spawning_totals_no2011 <- spawn_table_summary %>%                                          # tabulate spawning ground data 
  group_by(rearing_lake, year) %>%                                                         # by year
  dplyr::select(-natural_sockeye) %>% 
  spread(key = rearing_lake, value = total_sockeye, fill = 0) %>% 
  rename(oso_total = Osoyoos, ska_total = Skaha) %>% 
  left_join(spawn_table_summary %>% 
  dplyr::select(-total_sockeye) %>% 
  spread(key = rearing_lake, value = natural_sockeye, fill = 0) %>%
  rename(oso_nat = Osoyoos, ska_nat = Skaha)) %>%                                          # assign Osoyoos to oso_nat & Skaha to ska_nat vars 
  left_join(prop_oso_strays %>% dplyr::select(-spawning_location)) %>%                     # merge oso stray proportions and
  mutate(prop_oso_strays = ifelse(is.na(prop_oso_strays), 0, prop_oso_strays)) %>%         # set proportion to zero where NA
  left_join(prop_ska_strays) %>%                                                           # merge ska stray proportions and
  mutate(prop_ska_strays = ifelse(is.na(prop_ska_strays), 0, prop_ska_strays)) %>%         # set proportion to zero where NA
  mutate(oso_nat_origin = round(stray_correct(oso_nat, ska_nat, prop_oso_strays, prop_ska_strays))) %>%   # estimate OSO N-O taking into account OSO->SKA and SKA->OSO stray rates                        
  mutate(ska_nat_origin = round(stray_correct(ska_nat, oso_nat, prop_ska_strays, prop_oso_strays))) %>%   # estimate SKA N-O taking into account OSO->SKA and SKA->OSO stray rates 
  mutate(oso_strays = round(oso_nat_origin * prop_oso_strays)) %>%                                      
  mutate(ska_strays = round(ska_nat_origin * prop_ska_strays)) %>%
  mutate(prop_oso_origin_nat = round(oso_nat_origin/(oso_total + ska_total),3)) %>%
  mutate(prop_ska_origin_nat = round(ska_nat_origin/(oso_total + ska_total),3)) %>%
  filter(year != 2011)

#fit gam to impute missing 2011 N-O proportions by sub-stock
#perform cross validation to determine appropriate df on year spline
#restricting last year (i.e., gam_endyear) of analysis depending on availability of data (was 2021)

# gam_endyear <- 2021       ### years 2022 and 2023 not yet ready for analysis as spawners data not up-to-date [hs 240705] 
  gam_endyear <- last_year  ### years 2022 and 2023 now available from AO summary data (though not from raw AUC data) [hs 240801]
  
#For Osoyoos...filtering out early years where the proportion OSO is 1
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2006, year <= gam_endyear), formula = prop_oso_origin_nat ~ bs(year, 3)) # 3df gives lowest MSE <= 2023 
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2006, year <= gam_endyear), formula = prop_oso_origin_nat ~ bs(year, 4)) 
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2006, year <= gam_endyear), formula = prop_oso_origin_nat ~ bs(year, 5)) # 5df gives lowest MSE <= 2023 [241108]
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2006, year <= gam_endyear), formula = prop_oso_origin_nat ~ bs(year, 6)) # 6df gives lowest MSE <= 2021
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2006, year <= gam_endyear), formula = prop_oso_origin_nat ~ bs(year, 7))

#For Skaha, filtering out early years where the proportion SKA is 0
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2011, year <= gam_endyear), formula = prop_ska_origin_nat ~ bs(year, 3)) # 3df gives lowest MSE <= 2023 [241107]
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2011, year <= gam_endyear), formula = prop_ska_origin_nat ~ bs(year, 4)) # 4df gives lowest MSE <= 2021 [241108]
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2011, year <= gam_endyear), formula = prop_ska_origin_nat ~ bs(year, 5))
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2011, year <= gam_endyear), formula = prop_ska_origin_nat ~ bs(year, 6)) 
cv_gam_loo(data = spawning_totals_no2011 %>% filter(year > 2011, year <= gam_endyear), formula = prop_ska_origin_nat ~ bs(year, 7))

### Assign degrees of freedom for prop_oso_natural_m gam models below based on LOO analyses above...
if(gam_endyear == 2021) {            # if using original data restricted to <2022
  oso_df <- 6                        # use these df's
  ska_df <- 4
} else {                             # otherwise assign these df's based on data up to and including 2023
  oso_df <- 5
  ska_df <- 3
}
prop_oso_natural_m <- gam(prop_oso_origin_nat ~ bs(year, oso_df), data = spawning_totals_no2011 %>% 
                            filter(year > 2006, year <= gam_endyear), family = binomial(link = "logit"))  # OSO imputation model for data up to 2023
prop_ska_natural_m <- gam(prop_ska_origin_nat ~ bs(year, ska_df), data = spawning_totals_no2011 %>% 
                            filter(year > 2010, year <= gam_endyear), family = binomial(link = "logit"))  # SKA imputation model for data up to 2023

spawning_totals <- bind_rows(spawning_totals_no2011 %>% mutate(prop_natural_origin_type = "sampled"),   # incorporate 2011 estimates into spawn totals 
                              data.frame(prop_oso_origin_nat = predict(prop_oso_natural_m, data.frame(year = 2011), type = "response"), 
                                         prop_ska_origin_nat = predict(prop_ska_natural_m, data.frame(year = 2011), type = "response"),
                                         year = 2011, prop_natural_origin_type = "imputed")) %>% 
    arrange(year)

# spawning_totals_fix2011 <- spawning_totals %>%
#   group_by(year) %>%
#   mutate(oso_total = ifelse(year == 2011, 35900, round(oso_total,0))) %>%                               ### hardwire OSO spawner numbers for 2011
#   mutate(ska_total = ifelse(year == 2011,  9426, round(ska_total,0))) %>%                               ### hardwire OSO spawner numbers for 2011
#   mutate(oso_nat = round(ifelse(year == 2011, oso_total * prop_oso_origin_nat, oso_nat),0)) %>%         ### update   OSO N-O     numbers for 2011
#   mutate(ska_nat = round(ifelse(year == 2011, ska_total * prop_ska_origin_nat, ska_nat),0)) %>%         ### update   OSO N-O     numbers for 2011
#   mutate(prop_oso_strays = ifelse(year == 2011, prop_oso_strays_mean, prop_oso_strays)) %>%             ### update   OSO stray proport'n for 2011
#   mutate(prop_ska_strays = ifelse(year == 2011, wmean_ska_stray_prop, prop_ska_strays)) %>%             ### update   SKA stray proport'n for 2011
#   mutate(oso_nat_origin = round(ifelse(year == 2011,                                                    
#                                        stray_correct(oso_nat,ska_nat,prop_oso_strays,prop_ska_strays),  # estimate OSO N-O taking into account OSO->SKA and SKA->OSO stray rates  
#                                        oso_nat_origin),0)) %>%                                                     
#   mutate(ska_nat_origin = round(ifelse(year == 2011, 
#                                        stray_correct(ska_nat,oso_nat,prop_ska_strays,prop_oso_strays),  # estimate SKA N-O taking into account OSO->SKA and SKA->OSO stray rates 
#                                        ska_nat_origin),0)) %>%   
#   mutate(oso_strays     = round(ifelse(year == 2011, oso_nat_origin * prop_oso_strays, oso_strays),0)) %>%                                      
#   mutate(ska_strays     = round(ifelse(year == 2011, ska_nat_origin * prop_ska_strays, ska_strays),0)) %>%
#   mutate(prop_oso_origin_nat =  ifelse(year == 2011, oso_nat_origin/(oso_total + ska_total), prop_oso_origin_nat)) %>%
#   mutate(prop_ska_origin_nat =  ifelse(year == 2011, ska_nat_origin/(oso_total + ska_total), prop_ska_origin_nat)) %>%
#   arrange(year)

# spawning_totals <- spawning_totals_fix2011 %>%
spawning_totals <- spawning_totals %>%
  mutate(p_nat_oso = oso_nat / oso_total) %>%                                   # added recalc of (lost) initial sub-stock proportion natural for OSO [240915]
  mutate(p_nat_ska = ifelse(ska_total == 0, 0, ska_nat / ska_total))            # added recalc of (lost) initial sub-stock proportion natural for SKA [240915]

spawning_totals %>% 
  ggplot(aes(x = year, y = prop_oso_origin_nat, color = prop_natural_origin_type))+
# geom_smooth(method = "gam", formula = y ~ bs(x, 6), method.args = list(family = binomial(link = "logit")), se = FALSE)+
  geom_point(size=2)+
  geom_line()+
  scale_x_continuous(breaks = c(seq(from = 2000, to = last_year, by = 2)))+
  labs(title="Osoyoos Sockeye Natural Origin")+
  ylab("Proportion")+
  xlab(NULL)+
  theme_pt()+
  theme_pt(major_grid=TRUE)+
  theme(legend.position = "bottom", legend.title = element_text(size=9),
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

spawning_totals %>%                                                                      # plot proportion OSO N-O
  ggplot(aes(x = year, y = prop_ska_origin_nat, color = prop_natural_origin_type))+
  geom_line()+
# geom_smooth(method = "gam", formula = y ~ bs(x, 6), method.args = list(family = binomial(link = "logit")), se = FALSE)+
  geom_point(size=2)+
  scale_x_continuous(breaks = c(seq(from = 2000, to = last_year, by = 2)))+
  labs(title="Skaha Sockeye Natural Origin")+
  ylab("Proportion")+
  xlab("Return Year")+
  theme_pt()+
  theme_pt(major_grid=TRUE)+
  theme(legend.position = "bottom", legend.title = element_text(size=9),
        legend.background = element_rect(fill="white", colour="grey80", linewidth = 0.5))

### add stacked 100% plot for OSO/SKA proportions?

# filename <- paste("../output/Spawning_Totals_", timestamp, ".csv", sep = "")    
# write.csv(spawning_totals, filename)                                            

spawn_table_for_appendix <- spawning_totals %>%
  mutate(OsoProportionNatural = oso_nat / oso_total) %>%
  mutate(SkaProportionNatural = ska_nat / ska_total) %>%
  mutate(HatcheryProportion = 1 - (prop_oso_origin_nat + prop_ska_origin_nat)) %>%
  select(Year=year, 
         OsoSoxSpawners = oso_total, OsoProportionNatural, OsoNaturalSpawners = oso_nat, 
         SkaSoxSpawners = ska_total, SkaProportionNatural, SkaNaturalSpawners = ska_nat,
         OsoStrayProp = prop_oso_strays, OsoStrays = oso_strays, 
         SkaStrayProp = prop_ska_strays, SkaStrays = ska_strays,
         OsoNaturalOrigin = oso_nat_origin, SkaNaturalOrigin = ska_nat_origin,
         OsoBestPropNaturalOrigin = prop_oso_origin_nat, SkaBestPropNaturalOrigin = prop_ska_origin_nat,
         HatcheryProportion)

filename <- paste("../output/Spawning_Totals_", timestamp, ".csv", sep = "")    # filename for Spawning Grounds calculation 
write.csv(spawn_table_for_appendix, filename)                                   # for Appendix Table 

  
```  

```{r columbia/okanagan recruitment}  
#calculate recruits
columbia_okanagan_recruits <- annual_returns %>% ungroup() %>%
  left_join(spawning_totals %>% dplyr::rename(return_year = year)) %>% 
  mutate(oka_recruits = oka_sox) %>%                                                                          # Oka-bound SK at mouth of Columbia
  mutate(wen_recruits = mid_columbia_sox - oka_recruits) %>%                                                  # Wen-bound SK at mouth of Columbia
  mutate(prop_oso_origin_nat = ifelse(is.na(prop_oso_origin_nat), 1, round(prop_oso_origin_nat,3))) %>% 
  mutate(prop_ska_origin_nat = ifelse(is.na(prop_ska_origin_nat), 0, round(prop_ska_origin_nat,5))) %>%
  mutate(oso_nat_recruits = round(oka_recruits * prop_oso_origin_nat, 0),                                     # tidy up early years
         ska_nat_recruits = round(oka_recruits * prop_ska_origin_nat, 0)) %>%  
  mutate(hatchery_recruits = round(oka_recruits - oso_nat_recruits - ska_nat_recruits, 0)) %>%                # SKA H-O abundance
  mutate(ska_total_recruits = ifelse(return_year == 2013, ska_nat_recruits + 0.5 * hatchery_recruits,         # SKA total = H-O + N-O (presuming 50% of H-O returns in RY2013 --> SKA (since half of BY2009 releases were in SKA and half in OSO lake...
                              ifelse(return_year %in% c(2015, 2016, 2017), ska_nat_recruits,                  #                        whereas in RY2015 & 2016, all H-O returns were of OSO origin, so add none to Skaha...
                                     ska_nat_recruits + hatchery_recruits)))  %>%                             #                        otherwise, for all other years, set SKA Total Recruits = SKA N-O + H-O
  mutate(oso_total_recruits = ifelse(return_year == 2013, oso_nat_recruits + 0.5 * hatchery_recruits,         # OSO total = H-O + N-O (presuming 50% of H-O returns in RY2013 --> OSO (since half of BY2009 releases were in OSO and half in SKA lake...
                              ifelse(return_year %in% c(2015, 2016, 2017),                                    #                        whereas in RY2015 & 2016, all H-O returns were of OSO origin, so add all to Osoyoos...
                                     oso_nat_recruits + hatchery_recruits, oso_nat_recruits))) %>%            #                        otherwise, for all other years, set OSO Total Recruits = OSO N-O
  mutate(prop_hatch_origin = round(hatchery_recruits / (oso_total_recruits + ska_total_recruits), 3)) %>%     # calc prop H-O of all Oka sox
  mutate(prop_hatch_of_ska = ifelse(return_year %in% c(2007, 2015, 2016, 2017), 0,                            # calc prop H-O of SKA sox, zeroing early years (no SKA sox) & also 2015-2017 since H-O were OSO-origin
                                    round(ifelse(return_year == 2013,                                         #                        and adjusting for half-n-half distn of H-O in OSO & SKA in 2013
                                                 hatchery_recruits * 0.5, hatchery_recruits) / 
                                                 ska_total_recruits, 3))) %>%  
  mutate(prop_hatch_of_ska = ifelse(is.nan(prop_hatch_of_ska), 0, prop_hatch_of_ska)) %>%
  dplyr::select(return_year, total_harvest_below_bonn, bon_sox, columbia_recruits=columbia_sox, 
                snake_recruits = snake_sox, 
                mid_columbia_recruits = mid_columbia_sox, ok_stock_comp, wen_recruits, oka_recruits,  
                prop_oso_origin_nat, oso_nat_recruits, oso_total_recruits, 
                prop_ska_origin_nat, ska_nat_recruits, ska_total_recruits, 
                hatchery_recruits, prop_hatch_origin, prop_hatch_of_ska) 

filename <- paste("../output/Columbia_Sockeye_Returns_", timestamp, ".csv", sep = "")                 # filename for recruitment output 
write.csv(columbia_okanagan_recruits, filename)                                                       # saves the data to filename

columbia_stock_recruitment <- columbia_okanagan_recruits %>%                                          # summary output for SAR report Table 1 (RESULTS)
  dplyr::select(Year=return_year, 
                "Bon 24-hr Counts (estimated)" = bon_sox,
                "Harvest Zones 1-5" = total_harvest_below_bonn,
                "Snake Sockeye Estimates" = snake_recruits,
                "Mid-Columbia Sockeye Abundance" = mid_columbia_recruits,
                "Okanagan Stock Proportion (%)" = ok_stock_comp,
                "Wenatchee Sockeye" = wen_recruits,                                                   # Wenatchee recruitment not needed for Table 1
                "Okanagan Sockeye" = oka_recruits,
                "Osoyoos Natural Proportion (%)" = prop_oso_origin_nat,
                "Osoyoos Natural Recruits" = oso_nat_recruits,
                "Osoyoos Total Recruits" = oso_total_recruits)

filename <- paste("../output/Osoyoos_Sockeye_Recruits_Table1_", timestamp, ".csv", sep = "")          # filename for recruitment output 
write.csv(columbia_stock_recruitment, filename)                                                       # saves the data to filename

# create a stacked 100% plot comparing "Okanagan Sockeye" and "Wenatchee Sockeye"
long_data <- melt(columbia_stock_recruitment, id.vars = "Year", measure.vars = c("Okanagan Sockeye", "Wenatchee Sockeye"))
ggplot(long_data, aes(x = Year, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Return Year", y = "Proportion", Group = "Stock", fill = "Group",
       title = "Mid-Columbia Sockeye Stock Composition", subtitle = "By Return Year") +
  scale_fill_discrete(labels = c("Okanagan", "Wenatchee")) +
  theme_pt(major_grid=TRUE)+theme(legend.position="bottom") +
  theme(legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 10)) +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))    

filename <- paste("../figures/Mid-Columbia_Stock_Comp_", timestamp, ".png", sep = "") # filename for figure output 
ggsave(file = filename, width = 8, height = 6, units = "in")                          # saves the plot to filename

okanagan_substock_recruitment <- columbia_okanagan_recruits %>%
  mutate("Total Proportions" = prop_oso_origin_nat + prop_ska_origin_nat + prop_hatch_origin) %>%
  dplyr::select(Year = return_year, 
                "Okanagan-Bound Sockeye" = oka_recruits, 
                "Hatchery Origin Proportion (%)" = prop_hatch_origin,
                "Osoyoos Natural Proportion (%)" = prop_oso_origin_nat,
                "Skaha Natural Proportion (%)" = prop_ska_origin_nat,
#               "Total Proportions",
                "Hatchery-Origin" = hatchery_recruits,
                "Osoyoos Natural-Origin" = oso_nat_recruits,
                "Osoyoos Natural + Hatchery-Origin" = oso_total_recruits,
                "Skaha Natural-Origin" = ska_nat_recruits,
                "Skaha Natural + Hatchery-Origin" = ska_total_recruits)

filename <- paste("../output/OSO_SKA_Recruitment_", timestamp, ".csv", sep = "")                      # filename for OSO and SKA recruits
write.csv(okanagan_substock_recruitment, filename)                                                    # possible APPENDIX table
                
# columbia_okanagan_recruits %>%                                                                      # replaced with multi-line plot for all variables or
#   dplyr::select(return_year, columbia_recruits, oka_recruits, oso_nat_recruits, ska_nat_recruits,   # stacked 100% barchart for Okanagan sub-stocks, below
#                 hatchery_recruits) %>% 
#   gather(key = population, value = sockeye, -return_year) %>% 
#   ggplot(aes(x = return_year, y = sockeye))+
#   geom_line()+
#   scale_x_continuous(breaks = c(seq(from = 1975, to = 2025, by = 5)))+
# # scale_y_continuous(labels = scales::label_comma(trim = TRUE))+
#   scale_y_continuous(labels = label_number(suffix = "", scale = 1e-3))+
# # ylab(label = "Sockeye (thousands)")+
# # xlab(label = "Return Year") +
# # title(main="Sockeye Abundance (x1000) by Return Year",xlab=NULL, ylab=NULL)+
#   labs(title="Columbia/Okanagan Sockeye Recruits", subtitle = "by Return Year", 
#                                 x="", y = "Sockeye Recruit Abundance (1000s)")+
#   facet_wrap(~population, ncol=1)+
#   theme_pt(major_grid=TRUE)+
#   ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle

columbia_okanagan_long <- columbia_okanagan_recruits %>%                        # long format for multi-line plot
  dplyr::select(Year=return_year, Columbia=columbia_recruits, Okanagan=oka_recruits, 
                Osoyoos_Natural=oso_nat_recruits, Skaha_Natural=ska_nat_recruits, 
                Hatchery_Origin=hatchery_recruits) %>% 
  pivot_longer(cols = -Year, names_to = "Group", values_to = "Recruits")

ggplot(columbia_okanagan_long,
       aes(x=Year, y = Recruits/1000, color = Group))+  # multi-line plot of Columbia Sockeye recruits by sub-group
  geom_line() +
# geom_bar(stat = "identity", position = "dodge") +  
  scale_y_continuous(breaks       = c( 0, 100, 200, 300, 400, 500, 600, 700))+
  scale_x_continuous(breaks = c(seq(from = 1976, to = last_year+1, by = 4)))+
  labs(title="Columbia/Okanagan Sockeye Recruits", subtitle = "by Return Year", x="", y = "Abundance (1000s)")+
  theme_pt(major_grid=TRUE)+theme(legend.position="bottom") +
  theme(legend.background = element_rect(fill = "white", color = "black"),
    legend.title = element_blank(),    legend.text = element_text(size = 10)) +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle
  
filename <- paste("../figures/Columbia_Okanagan_Recruits_", timestamp, ".png", sep = "") # filename for figure output 
ggsave(file = filename, width = 8, height = 6, units = "in")                    # saves the plot to filename

okanagan_recruits_long <- columbia_okanagan_long %>%                            # set up data for stacked bar plot 
  filter(Group %in% c("Osoyoos_Natural", "Skaha_Natural", "Hatchery_Origin"))%>%
  group_by(Year) %>%
  mutate(Group = replace(Group, Group == "Osoyoos_Natural", "1. Osoyoos Natural")) %>%
  mutate(Group = replace(Group, Group == "Skaha_Natural",   "2. Skaha Natural"))   %>%
  mutate(Group = replace(Group, Group == "Hatchery_Origin", "3. Hatchery Origin")) %>%
  mutate(Proportion = Recruits / sum(Recruits))

ggplot(okanagan_recruits_long %>% filter(Year > 2003),                          # cluster bar plot of Okanagan Sockeye recruits by sub-group
       aes(x = factor(Year), y = Recruits/1000, fill = Group)) +
  geom_bar(stat = "identity", position = "dodge", color="black") +
  scale_y_continuous(breaks       = c( 0, 100, 200, 300, 400, 500, 600, 700))+
# scale_y_continuous(labels = scales::percent, expand = c(0,0)) +               # format props as % and get rid of white space between data and plot borders
  labs(x = "", y = "Abundance (1000s)") +
  scale_x_discrete(breaks = c(seq(from = 2004, to = last_year+1, by = 2))) +
  labs(title="Okanagan Sockeye Recruitment", subtitle = "by Return Year")+
  theme_minimal() +
# scale_color_manual(values = c("white", "red", "gray"))+                       ### can't seem to change bars to these colours... 
  scale_fill_brewer(palette = "Set2") +
  theme(plot.title = element_text(hjust=0.5), legend.position = "bottom",
        plot.subtitle = element_text(hjust=0.5), axis.ticks.x = element_line(color = "black"),
        legend.title = element_blank(),    legend.text = element_text(size = 10))              

filename <- paste("../figures/Oka_Substock_Recruit_Cluster_", timestamp, ".png", sep = "") # filename for figure output 
ggsave(file = filename, width = 8, height = 4, units = "in")                           # saves the plot to filename

ggplot(okanagan_recruits_long,                                                  # stacked bar plot of Okanagan Sockeye recruitment by sub-group
       aes(x = factor(Year), y = Proportion, fill = Group)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent, expand = c(0,0)) +               # format props as % and get rid of white space between data and plot borders
  labs(x = "", y = "Proportion") +
  scale_x_discrete(breaks = c(seq(from = 1976, to = last_year+1, by = 4))) +
  labs(title="Okanagan Sockeye Recruitment Proportions", subtitle = "by Return Year")+
  theme_minimal() +
#  scale_color_manual(values = c("white", "red", "gray"))+                      ### can't seem to change bars to these colours... 
  scale_fill_brewer(palette = "Set2") +
  theme(plot.title = element_text(hjust=0.5), legend.position = "bottom",
        plot.subtitle = element_text(hjust=0.5), axis.ticks.x = element_line(color = "black"),
        legend.title = element_blank(),    legend.text = element_text(size = 10))              

filename <- paste("../figures/Oka_Substock_Recruitment_", timestamp, ".png", sep = "") # filename for figure output 
ggsave(file = filename, width = 8, height = 4, units = "in")                           # saves the plot to filename

# geometric mean before and after FWMT implementation - note, 2008 is first year where we might expect to see difference in adult returns  
pre_fwmt  <- geometric.mean(columbia_okanagan_recruits[columbia_okanagan_recruits$return_year %in% c(1977:2007),]$oso_nat_recruits)/1000
post_fwmt <- geometric.mean(columbia_okanagan_recruits[columbia_okanagan_recruits$return_year %in% c(2008:last_year),]$oso_nat_recruits)/1000 ### compute geometric mean ###

# plot recruits through time
columbia_okanagan_recruits %>% ggplot(aes(x = return_year, y = oso_nat_recruits/1000))+
  geom_line(linewidth = 0.5)+
  geom_point(size = 2)+
  geom_segment(aes(x = 1976,   xend = 2007.5, y = pre_fwmt,  yend = pre_fwmt),  colour = brewer.pal(8, "Set1")[1], linewidth = 1, linetype = "dashed")+ # CB: this is for the option of adding the pre- and current freshwater management tools era 
  geom_segment(aes(x = 2007.5, xend = 2024,   y = post_fwmt, yend = post_fwmt), colour = brewer.pal(8, "Set1")[2], linewidth = 1, linetype = "dashed")+ #     to compare median recruits between the two time periods
  geom_hline(yintercept = geometric.mean(columbia_okanagan_recruits$oso_nat_recruits)/1000, colour="black", linewidth = 1, linetype = "dotdash")+
  scale_y_continuous(breaks       = c( 0, 100, 200, 300, 400, 500, 600))+
  scale_x_continuous(breaks = c(seq(from = 1976, to = last_year+1, by = 4)))+
  labs(title="Osoyoos Sockeye Recruits", subtitle = "by Return Year", x="", y = "Sockeye Recruit Abundance (1000s)")+
  theme_pt(major_grid=TRUE)+
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5)) 
  
filename <- paste("../figures/OSO_Recruits_", timestamp, ".png", sep = "")      # filename for figure output 
ggsave(file = filename, width = 6, height = 4, units = "in")                    # saves the plot to filename

# create timeseries of return year and number of total okanagan, osoyoos & skaha sub-stock recruits, and write to a CSV file
oka_recruits <- columbia_okanagan_recruits %>% 
  dplyr::select(return_year, oka_recruits, hatchery_recruits, 
                oso_nat_recruits, oso_total_recruits,
                ska_nat_recruits, ska_total_recruits)

filename <- paste("../output/Oka_Recruits_", timestamp, ".csv", sep = "")       # filename for recruitment output 
write.csv(oka_recruits, filename)                                               # saves the data to filename
```  

```{r juvenile abund}

# #Pre-smolt abundance
# juv_dat <- read_excel("../data/SIS - Data - OSOYOOS - 24.07.24.xlsx", sheet = "Juvenile Data") #presmolt (was 24.06.24.xlsx) [hs: 240807]
# j_dat <- juv_dat[c(3:nrow(juv_dat)),c(2,6)] %>%         # grabbing the appropriate columns from the excel file
#   dplyr::select(smolt_year = `Smolt Migration Year`, no_smolt = `...6`) %>%
#   mutate_at("no_smolt", as.numeric) %>%                 # selecting columns and converting no_smolt to numeric
#   filter(smolt_year >=1998, smolt_year <= last_year)
# write.csv(j_dat,  "../data/juv_dat_xlsx_240624.csv")    # if juv data imported, re-write to CSV  ### comment out for GitHub

j_dat <- read.csv("../data/juv_dat_xlsx_240624.csv")    # replaces import data from SIS-OSO xlsx workbook # keep for GitHub [240510]

```

```{r age composition}

age_comp_ONA_CRITFC <- read.csv2("../data/age_comp_ona_critfc.csv", sep=",")    ### see/run "Age Composition - ONA vs CRITFC.R" for source of age_comp_ONA_CRITFC ###     

age_proportions_ONA_CRITFC <- age_comp_ONA_CRITFC %>%                        
    dplyr::select(return_year, age_class,
                  ONA_prop_at_age, ONA_method, 
                  CRITFC_prop_at_age, CRITFC_method) %>%
    mutate(Age = as.numeric(substr(age_class, 10, 13))) %>%
    mutate(best_source_old = ifelse(return_year %in% c(1985,1987:2000,2002:2005,
                                                       2013, 2015),               # next, create best_source_new assignment variable by setting all years specified here to CRITFC...
                                   "CRITFC", "UNKNOWN")) %>%
    mutate(best_source_old = ifelse(return_year %in% c(2001,2006:2012,            # ...and all years specified here to ONA, 
                                                       2014,2016:2023),           #  
                                   "ONA", best_source_old)) %>%
    mutate(best_source_old = ifelse(return_year %in% c(1980:1984,1986),           # ... multi-year averages (1980-1984, 1986)
                                   "Average", best_source_old)) %>%
  # mutate(best_source_new = ifelse(return_year %in% c(1985,1987:2001,2004:2023), # OBSOLETE as this assigned 2002-2003 to ONA [240825]; create best_source_new assignment variable by setting all years specified here to CRITFC...
  #                                "CRITFC", "UNKNOWN")) %>%
    mutate(best_source_new = ifelse(return_year %in% c(1985,1987:last_year),      # next, create best_source_new assignment variable by setting all years specified here to CRITFC...
                                   "CRITFC", "UNKNOWN")) %>%
  # mutate(best_source_new = ifelse(return_year %in% c(2002:2003, 2007),          # ...and all years specified here to ONA...  
    # mutate(best_source_new = ifelse(return_year %in% c(2002:2003),              # ...and all years specified here to ONA...  
    #                                "ONA", best_source_new)) %>%
    mutate(best_source_new = ifelse(return_year %in% c(1980:1984,1986),           # ... multi-year averages (1980-1984, 1986)
                                   "Average", best_source_new)) %>%
    mutate(CRITFC_prop_at_age = as.numeric(CRITFC_prop_at_age)) %>%
    mutate(ONA_prop_at_age    = as.numeric(ONA_prop_at_age))
                
age_data_old <- age_proportions_ONA_CRITFC %>%
  mutate(best_source     = best_source_old)                                     ### select OLD annual assignments to use in analysis below, OR...

age_data_new <- age_proportions_ONA_CRITFC %>%
  mutate(best_source     = best_source_new)                                     ### select NEW annual assignments to use in analysis below

#--- OLD age comp assignments... 

# age_data.df <- age_data_old %>% 
#   mutate(ocean_age = str_sub(Age, start = -1)) %>% 
#   group_by(return_year, ocean_age, best_source) %>% 
#   summarise(CRITFC_prop_at_age = sum(CRITFC_prop_at_age, na.rm = TRUE), 
#             ONA_prop_at_age = sum(ONA_prop_at_age, na.rm = TRUE)) %>% 
#   mutate(best_age_prop = ifelse(best_source == "CRITFC", CRITFC_prop_at_age, ONA_prop_at_age))
# 
# age_prop_chk <- age_data.df %>%                                                 # shows if any annual total age proportions don't add up to 1.0
#   group_by(return_year) %>%                                                     # sorted by total_best proportion
#   summarise(total_best = sum(best_age_prop), 
#             total_ONA  = sum(ONA_prop_at_age), 
#             total_CRITFC  = sum(CRITFC_prop_at_age)) %>% 
#   arrange(total_best)
# 
# # Following plots check the age composition visually.  First one shows selected proportions by ocean age with annual assignment source
# ggplot(age_data.df, aes(x = return_year, y = best_age_prop))+                   #stacked 100% bar plot of annual age composition
#   geom_point(data = age_data.df %>% ungroup() %>% 
#              dplyr::select(return_year, best_source) %>% unique(), 
#              aes(x = return_year, y = -0.02, color = best_source), 
#              size = 3, pch = 15)+
#   geom_col(aes(fill = ocean_age))+
#   scale_fill_viridis_d("Ocean Age")+
#   scale_color_manual(values = c("black", "red", "dodgerblue", "green"), "Source")+
#   guides(colour = guide_legend(order = 2),
#           fill = guide_legend(order = 1))+
#   coord_cartesian(expand = FALSE)+
#   labs(title = "Ocean Age Composition (OLD)", subtitle = "By Return Year")+
#   ylab("Proportion at Age")+
#   xlab("")+
#   theme_pt(major_grid=TRUE)+
#   ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle
# 
# filename <- paste("../figures/Age_Composition_(OLD)_", timestamp, ".png", sep = "")   # filename for figure output
# ggsave(file = filename, width = 6, height = 4, units = "in")                    # saves the plot to filename
# 
# age_data.df %>%                                                                 # compare SiRE/ONA vs CRITFC/Fryer annual age comp% by ocean age
#   dplyr::select(-best_age_prop) %>% 
#   gather(key = type, value = prop, prop_Fryer:prop_SIRE) %>%
#   mutate(type = str_remove(type, "prop_")) %>% 
#   mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")) %>% 
# ggplot(aes(x = return_year, y = prop))+
#   geom_point(data = age_data.df %>% mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")), aes(y = best_age_prop), size = 2)+
#   geom_line(data = age_data.df %>%  mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")), aes(y = best_age_prop))+
#   geom_point(pch = 16, size = 1.5, aes(color = type))+
#   facet_grid(ocean_age~.)+
#   scale_color_manual(values = c("red", "dodgerblue"), "source")+
#   scale_fill_manual( values = c("red", "dodgerblue"), "source")+
#   ylab("Ocean age proportion")+
#   xlab("Return year")+
#   scale_x_continuous(breaks = seq(1980, last_year, by = 4))+
#   scale_y_continuous(limits = c(0, 1))+
#   theme_pt(major_grid=TRUE)+
#   ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle
# 
# filename <- paste("../figures/Compare_SiRE_Fryer_Age_Comp_", timestamp, ".png", sep = "")   # filename for figure output 
# ggsave(file = filename, width = 6, height = 6, units = "in")                                # saves the plot to filename

#--- NEW age comp assignments... 

age_data.df <- age_data_new %>% 
  filter(return_year != 1986) %>%
  mutate(ocean_age = str_sub(Age, start = -1)) %>% 
  group_by(return_year, ocean_age, best_source) %>% 
  summarise(CRITFC_prop_at_age = sum(CRITFC_prop_at_age, na.rm = TRUE), 
            ONA_prop_at_age = sum(ONA_prop_at_age, na.rm = TRUE)) %>% 
  mutate(best_age_prop = ifelse(best_source == "CRITFC", CRITFC_prop_at_age, ONA_prop_at_age)) %>%
  filter(return_year > 1984)

filename <- paste("../output/Ocean_Age_Comp_", timestamp, ".csv", sep = "")     # output data for report
write.csv(age_data.df, filename)                                                # saves the data to filename

age_data.df <- age_data.df %>%
  group_by(return_year) %>%
  mutate(prop = best_age_prop / sum(best_age_prop))

ggplot(age_data.df, aes(x = return_year, y = prop, fill = as.factor(ocean_age))) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Return Year", y = "Percentage", fill = "Ocean Age") +
  scale_x_continuous(breaks = c(seq(from = 1985, to = last_year, by = 3))) +
  scale_fill_viridis_d("Ocean Age (Years)")+
  labs(title = "Okanagan Sockeye Ocean Age Composition", subtitle = "By Return Year")+
  ylab("Percent at Age")+
  xlab("")+
  theme_pt(major_grid=TRUE)+theme(legend.position="bottom") +
  theme(legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 10)) +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle

# age_prop_chk <- age_data.df %>%                                                 # shows if any annual total age proportions don't add up to 1.0
#   group_by(return_year) %>%                                                     # sorted by total_best proportion
#   # summarise(total_best    = sum(best_age_prop), 
#   #           total_ONA     = sum(ONA_prop_at_age), 
#   #           total_CRITFC  = sum(CRITFC_prop_at_age)) %>% 
#   summarise(total_best      = sum(best_age_prop)) %>% 
#   arrange(return_year) # total_best)
# 
# # Following plots check the age composition visually.  First one shows selected proportions by ocean age with annual assignment source
# ggplot(age_data.df, aes(x = return_year, y = best_age_prop))+                   #stacked 100% bar plot of annual age composition
#   geom_point(data = age_data.df %>% ungroup() %>% 
# #              filter(return_year != 1986) %>%
#                dplyr::select(return_year, best_source) %>% 
#                unique(), aes(x = return_year, y = 0, 
#                              color = best_source), size = 3, pch = 15)+
#   geom_col(aes(fill = ocean_age))+
#   scale_fill_viridis_d("Ocean Age (Years)")+
#   scale_color_manual(values = c("black", "red", "dodgerblue", "green"), "Source")+
#   guides(colour = guide_legend(order = 2),
#            fill = guide_legend(order = 1))+
# # coord_cartesian(expand = FALSE)+
# # coord_cartesian(xlim = c(1986, last_year)) +
#   scale_x_continuous(breaks = c(seq(from = 1985, to = last_year, by = 3))) +
#   labs(title = "Okanagan Sockeye Ocean Age Composition", subtitle = "By Return Year")+
#   ylab("Proportion at Age")+
#   xlab("")+
#   theme_pt(major_grid=TRUE)+theme(legend.position="bottom") +
#   theme(legend.background = element_rect(fill = "white", color = "black"),
#         legend.text = element_text(size = 10)) +
#   ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle


filename <- paste("../figures/Age_Composition_(NEW)_", timestamp, ".png", sep = "")   # filename for figure output
ggsave(file = filename, width = 8, height = 6, units = "in")                    # saves the plot to filename
# 
# age_data.df %>%                                                               # compare SiRE/ONA vs CRITFC/Fryer annual age comp% by ocean age
#   dplyr::select(-best_age_prop) %>% 
#   gather(key = type, value = prop, prop_Fryer:prop_SIRE) %>%
#   mutate(type = str_remove(type, "prop_")) %>% 
#   mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")) %>% 
# ggplot(aes(x = return_year, y = prop))+
#   geom_point(data = age_data.df %>% mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")), aes(y = best_age_prop), size = 2)+
#   geom_line(data = age_data.df %>%  mutate(ocean_age = paste("Ocean age ", ocean_age, sep = "")), aes(y = best_age_prop))+
#   geom_point(pch = 16, size = 1.5, aes(color = type))+
#   facet_grid(ocean_age~.)+
#   scale_color_manual(values = c("red", "dodgerblue"), "source")+
#   scale_fill_manual( values = c("red", "dodgerblue"), "source")+
#   ylab("Ocean age proportion")+
#   xlab("Return year")+
#   scale_x_continuous(breaks = seq(1980, last_year, by = 4))+
#   scale_y_continuous(limits = c(0, 1))+
#   theme_pt()
# 
# filename <- paste("../figures/Compare_SiRE_Fryer_Age_Comp_", timestamp, ".png", sep = "")   # filename for figure output 
# ggsave(file = filename, width = 6, height = 6, units = "in")                                # saves the plot to filename

```



```{r marine survival}

# calculating marine survival by age composition source 

### OLD age comp ###

radat  <- left_join(oka_recruits %>% 
                    filter(return_year >= 1980) %>%
                    dplyr::select(return_year, oso_nat_recruits), 
                    age_data_old, by = "return_year") %>%                       # joining the recruitment dataframe with the OLD age composition data frame 
  mutate(ocean_age       = as.numeric(str_sub(Age, start = -1)),
         smolt_year      = return_year - ocean_age,
         sox_age_critfc  = oso_nat_recruits * CRITFC_prop_at_age,               # calculating the number of recruits according to each age composition source
         sox_age_sire    = oso_nat_recruits * ONA_prop_at_age,
         sox_age_best    = oso_nat_recruits * ifelse(best_source == "CRITFC", CRITFC_prop_at_age, ONA_prop_at_age),
         ONA_method      = ifelse(is.na(ONA_method), "None", ONA_method),
         CRITFC_method   = ifelse(is.na(CRITFC_method), "None", CRITFC_method))     
  radat[is.na(radat)] <- 0 

# check_radat_old <- radat %>% filter(smolt_year == 1999) %>%                   # quick check on returns at age calculations... 
#   dplyr::select(smolt_year, return_year, best_source, oso_nat_recruits, sox_age_critfc, sox_age_sire, sox_age_best)

radat2 <- radat %>%
  filter(smolt_year <= last_year - 2) %>%                                       # drop last year since returns of major age classes not complete
  group_by(smolt_year) %>% summarize(oso_sox_critfc = sum(sox_age_critfc),      # summing the recruits by smolt year
                                     oso_sox_sire   = sum(sox_age_sire),
                                     oso_sox_best   = sum(sox_age_best)) %>% 
  left_join(., j_dat, by = "smolt_year") %>%                                    # joining the juvenile dataframe
  filter(smolt_year > 1997) %>%                                                 # no juvenile abund data prior to 1998
  mutate(critfc_surv = oso_sox_critfc / no_smolt,                               # calculating marine survival
         sire_surv   = oso_sox_sire   / no_smolt,
         best_surv   = oso_sox_best   / no_smolt) %>%
  dplyr::select(smolt_year, critfc_surv, sire_surv, best_surv) %>%              # streamlining the dataset to the relevant columns
  pivot_longer(cols = ends_with("_surv"),                                       # arranging the data to long format for plotting
               names_to = "source",
               values_to = "survival")

#plotting marine survival time-series (OLD) with previous "BEST" time-series choice
ggplot(radat2, aes(x = smolt_year, y = survival, colour = source))+
  geom_point(aes(size = source, alpha = source))+
  geom_line(aes(linewidth = source, alpha = source))+
  scale_colour_manual(values = c("black","#0072B2", "#D55E00"), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_linewidth_manual(values = c(1, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_size_manual(values = c(1, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_alpha_manual(values = c(1, 0.3, 0.3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  geom_hline(yintercept = sum(radat2[radat2$source == "best_surv", 3])/nrow(radat2[radat2$source == "best_surv", 3]), colour = "red", alpha = 0.5)+
  scale_x_continuous(breaks = c(seq(from = 1998, to = last_year, by = 4)))+
  labs(title="Osoyoos Sockeye SAR (OLD)", subtitle = "by Smolt Year", 
       x="", y = "Annual Survival (proportion)")+
  theme_pt(major_grid=TRUE)+
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle

#saving the plot
filename <- paste("../figures/OSO_SAR_Survival_(OLD)_", timestamp, ".png", sep = "")   # filename for figure output 
ggsave(file = filename, width = 6, height = 4, units = "in")                           # saves the plot to filename

### NEW age comp ############################################################### 

oso_age_at_return <- left_join(oka_recruits %>%                                 # generate selected "FINAL" age at return calculations used for report
                     filter(return_year >= 1980) %>%
                     dplyr::select(return_year, oso_nat_recruits), 
                     age_data_new, by = "return_year") %>%                      # joining the recruitment dataframe with the NEW age composition data frame 
  mutate(ocean_age       = as.numeric(str_sub(Age, start = -1)),
         smolt_year      = return_year - ocean_age,
         sox_age_critfc  = oso_nat_recruits * CRITFC_prop_at_age,               # calculating the number of recruits according to each age composition source
         sox_age_sire    = oso_nat_recruits * ONA_prop_at_age,
         sox_age_best    = oso_nat_recruits * ifelse(best_source == "CRITFC", 
                                           CRITFC_prop_at_age, ONA_prop_at_age)) %>%
  dplyr::select(return_year, oso_nat_recruits, Age, ocean_age, smolt_year, 
                best_source, sox_age_best, sox_age_critfc, sox_age_sire)
  oso_age_at_return[is.na(oso_age_at_return)] <- 0 

oso_marine_survival_by_source <- oso_age_at_return %>%                          # gathering marine survival terms together for report
  group_by(smolt_year) %>% summarize(oso_sox_critfc = sum(sox_age_critfc),      # summing the recruits by smolt year
                                     oso_sox_sire   = sum(sox_age_sire),
                                     oso_sox_best   = sum(sox_age_best)) %>% 
  left_join(., j_dat, by = "smolt_year") %>%                                    # joining the juvenile dataframe
  filter(smolt_year >= 1998) %>%  filter(smolt_year <= last_year - 2) %>%       # no juvenile abund data prior to 1998 and incomplete returns at age in most recent years
  mutate(critfc_surv  = oso_sox_critfc / no_smolt,                              # calculating marine survival
         sire_surv    = oso_sox_sire   / no_smolt,
         best_surv    = oso_sox_best   / no_smolt,
         oso_sox_survival = best_surv, 
         oso_juv_presmolt = no_smolt) %>%
  dplyr::select(smolt_year, critfc_surv, sire_surv, best_surv,                  # streamlining the dataset to the relevant columns
                oso_sox_critfc, oso_sox_sire, oso_sox_best, oso_juv_presmolt,
                critfc_surv, sire_surv, best_surv, oso_sox_survival)  

filename <- paste("../output/OSO_Marine_Survival_Source_", 
                  timestamp, ".csv", sep = "")                                  # filename for CRITFC/ONA survival time-series output 
write.csv(oso_marine_survival_by_source,filename)                               # for report APPENDIX

mar_surv_table <- oso_marine_survival_by_source %>%                             # "Best" Marine Survival selected for output for report table 
  dplyr::select(Smolt_Year = smolt_year, 
                Presmolt_Estimates = oso_juv_presmolt, 
                Adult_Recruitment = oso_sox_best,
                Presmolt_to_Adult_Survival = oso_sox_survival)

filename <- paste("../output/OSO_Marine_Surv_for_Report_", 
                  timestamp, ".csv", sep = "")                                  # filename for SELECT survival time-series output 
write.csv(mar_surv_table, filename)                                             # for report TABLE

radat2_new <- oso_age_at_return %>%
  filter(smolt_year <= last_year - 2) %>%                                       # drop last year since returns of major age classes not complete
  group_by(smolt_year) %>% summarize(oso_sox_critfc = sum(sox_age_critfc),      # summing the recruits by smolt year
                                     oso_sox_sire   = sum(sox_age_sire),
                                     oso_sox_best   = sum(sox_age_best)) %>% 
  left_join(., j_dat, by = "smolt_year") %>%                                    # joining the juvenile dataframe
  filter(smolt_year > 1997) %>%                                                 # no juvenile abund data prior to 1998
  mutate(critfc_surv = oso_sox_critfc / no_smolt,                               # calculating marine survival
         sire_surv   = oso_sox_sire   / no_smolt,
         best_surv   = oso_sox_best   / no_smolt) %>%
  dplyr::select(smolt_year, critfc_surv, sire_surv, best_surv) %>%              # streamlining the dataset to the relevant columns
  pivot_longer(cols = ends_with("_surv"),                                       # arranging the data to long format for plotting
               names_to = "source",
               values_to = "survival")

#plotting marine survival time-series comparison (NEW) with current "BEST" time-series choice
ggplot(radat2_new, aes(x = smolt_year, y = survival, colour = source))+
  geom_point(aes(size = source, alpha = source))+
  geom_line(aes(linewidth = source, alpha = source))+
  scale_colour_manual(values = c("black","#0072B2", "#D55E00"), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
# scale_color_viridis(discrete = TRUE)  # Use a colorblind-friendly palette
  scale_linewidth_manual(values = c(1, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_size_manual(values = c(1, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_alpha_manual(values = c(1, 0.3, 0.3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  geom_hline(yintercept = geometric.mean(radat2_new[radat2_new$source == "best_surv", 3]), colour = "red", alpha = 0.5)+
  scale_x_continuous(breaks = c(seq(from = 1998, to = last_year, by = 2)))+
  labs(title="Osoyoos Sockeye SAR (NEW)", subtitle = "by Smolt Year", 
       x="", y = "Annual Survival (proportion)")+
  theme_pt(major_grid=TRUE)+
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle

#saving the plot
filename <- paste("../figures/OSO_SAR_Survival_(NEW)_", timestamp, ".png", sep = "")   # filename for figure output 
ggsave(file = filename, width = 6, height = 4, units = "in")                           # saves the plot to filename

#---------

radat2_final <- radat2_new %>% filter(source == "best_surv")                    # plot marine survival based on 'best' age-comp time-series

#plotting FINAL marine survival time-series (comparison (NEW) with current ("BEST")
ggplot(radat2_final, aes(x = smolt_year, y = survival, colour = source))+
  geom_line(aes(linewidth = source, alpha = source))+
  geom_point(aes(size = source, alpha = source, color="black"))+
  scale_colour_manual(values = c("lightblue","black", "#D55E00"), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_linewidth_manual(values = c(1, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_size_manual(values = c(2, 3, 3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  scale_alpha_manual(values = c(1, 0.3, 0.3), name = "Source", labels = c("Best", "CRITFC", "ONA/SIRE"))+
  geom_hline(yintercept = geometric.mean(radat2_final[radat2_final$source == "best_surv", 3]),
             colour = "red", alpha = 1, linetype = "dashed") + 
  scale_x_continuous(breaks = c(seq(from = 1998, to = last_year, by = 2)))+
  scale_y_continuous(labels = percent_format()) +
# labs(title="Osoyoos Sockeye SAR (FINAL)", subtitle = "by Smolt Year", 
  labs(title="Osoyoos Sockeye Presmolt-to-Adult Survival", subtitle = "by Smolt Year", 
       x="", y = "Survival (%)")+
  theme_pt(major_grid=TRUE)+theme(legend.position="none") +
  ggplot2::theme(plot.subtitle = ggplot2::element_text(hjust=0.5))              # theme_pt centers main title but not subtitle

#saving the plots
filename <- paste("../figures/OSO_SAR_Survival_(FINAL)_", timestamp, ".png", sep = "")   # filename for figure output 
ggsave(file = filename, width = 6, height = 4, units = "in")                             # saves the plot to filename

make_a_sound("coin", 0.1)   # signal end of execution
```
